apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoodyssee-api
  labels:
    app: videoodyssee-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: videoodyssee-api
  template:
    metadata:
      labels:
        app: videoodyssee-api
    spec:
      containers:
      - name: videoodyssee-api
        image: videoodyssee/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: videoodyssee-secrets
              key: jwt-secret
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: videoodyssee-secrets
              key: access-key
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: videoodyssee-secrets
              key: api-key
        envFrom:
        - configMapRef:
            name: videoodyssee-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: videoodyssee-api-service
spec:
  selector:
    app: videoodyssee-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: videoodyssee-config
data:
  VOCTOWEB_URL: "https://media.ccc.de"
  PIPELINE_URL: "https://videopipeline.freifunk.net/go/api/pipelines/processing-pipeline/schedule" 